# Generated by Django 4.2.24 on 2025-10-11 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_wasteitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('Household', 'Household'), ('Shop', 'Shop'), ('Hotel', 'Hotel')], default='Household', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='monthly_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.customer'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=50),
        ),
        migrations.DeleteModel(
            name='BillItem',
        ),
        migrations.DeleteModel(
            name='WasteItem',
        ),
    ]
