# Generated by Django 4.2.24 on 2025-10-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer_customer_type_customer_monthly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='month',
            field=models.CharField(default='January', max_length=20),
        ),
        migrations.AddField(
            model_name='bill',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('customer', 'month', 'year')},
        ),
    ]
