# Generated by Django 4.2.24 on 2025-10-11 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bill_month_bill_paid_bill_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='month',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.bill')),
                ('waste_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wasteitem')),
            ],
        ),
    ]
