# Generated by Django 4.2.24 on 2025-10-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_wasteitem_alter_bill_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
