# Generated by Django 4.2.24 on 2025-10-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_billitem_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
