# Generated by Django 5.2.4 on 2025-12-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customer_address_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='status',
        ),
        migrations.AlterField(
            model_name='bill',
            name='month',
            field=models.IntegerField(default=12),
        ),
    ]
