# Generated by Django 5.2.4 on 2025-12-30 11:03

from django.db import migrations, models
import random
import string


def generate_customer_ids(apps, schema_editor):
    Customer = apps.get_model('core', 'Customer')
    for customer in Customer.objects.all():
        if not customer.customer_id:
            customer.customer_id = 'CUST' + ''.join(random.choices(string.digits, k=6))
            customer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_status_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.RunPython(generate_customer_ids),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
