# Generated by Django 5.2.4 on 2025-12-30 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_customer_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
