# Generated by Django 5.2.4 on 2025-12-30 16:02

import random
import string
from django.db import migrations, models


def generate_customer_id():
    """Generate a unique customer ID"""
    return 'CUST' + ''.join(random.choices(string.digits, k=6))


def populate_customer_ids(apps, schema_editor):
    """Populate customer_id for existing customers"""
    Customer = apps.get_model('core', 'Customer')
    for customer in Customer.objects.all():
        if not customer.customer_id:
            # Generate unique customer_id
            while True:
                customer_id = generate_customer_id()
                if not Customer.objects.filter(customer_id=customer_id).exists():
                    customer.customer_id = customer_id
                    customer.save()
                    break


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_customer_customer_id_remove_customer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(populate_customer_ids),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
