# Generated by Django 5.2.4 on 2026-01-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20251230_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='month',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bill',
            name='year',
            field=models.IntegerField(default=2026),
        ),
    ]
